-- =====================================================================
-- Incident Management & Log Analysis System - Seed Data
-- =====================================================================
-- NOTE: application users (admin / analyst / customer accounts) are seeded
-- by the Spring DataSeeder at startup, because passwords must be bcrypt
-- hashes generated by the application's PasswordEncoder - NOT by this SQL.
--
-- This script only seeds static reference data. All statements use
-- INSERT IGNORE so the script is idempotent (duplicates are skipped via
-- the unique keys on sla_rules.priority and kb_articles.kb_number).
-- =====================================================================

USE imsdb;

-- ---------------------------------------------------------------------
-- SLA rules: resolution time (hours) per priority
-- ---------------------------------------------------------------------
INSERT IGNORE INTO sla_rules (priority, resolution_time_hours) VALUES
    ('P1',  4),
    ('P2',  8),
    ('P3', 24),
    ('P4', 72);

-- ---------------------------------------------------------------------
-- Sample knowledge base articles
-- ---------------------------------------------------------------------
INSERT IGNORE INTO kb_articles
    (kb_number, title, issue_description, root_cause, resolution, keywords, created_by, created_at, times_used)
VALUES
    ('KB-101',
     'Database connection timeouts under load',
     'Application requests intermittently fail with "Connection is not available, request timed out" errors during peak traffic. API latency spikes and incidents are raised for failed transactions.',
     'The database connection pool is exhausted: the configured maximum pool size is too small for peak concurrent load, and slow queries hold connections longer than expected.',
     '1. Increase the connection pool maximum size (e.g. HikariCP maximumPoolSize) to match peak concurrency.\n2. Lower connectionTimeout only after the pool is sized correctly.\n3. Identify and optimize slow queries holding connections (add indexes, fix N+1 queries).\n4. Verify the database server max_connections accommodates the new pool size across all app instances.',
     'database,timeout,connection pool,hikari,latency,db,exhausted',
     'system',
     NOW(),
     0),

    ('KB-102',
     'Authentication failures - users unable to log in',
     'Users receive "401 Unauthorized" or "Authentication service unavailable" errors at login. Failure rate is widespread rather than tied to individual accounts.',
     'The identity/authentication service is unhealthy - typically a hung service process or an expired/invalid TLS certificate breaking the trust chain between the app and the identity provider.',
     '1. Check identity service health and logs; restart the identity service if it is hung or unresponsive.\n2. Verify TLS certificates used by the identity provider and the service-to-service trust store: check expiry dates and renew/redeploy expired certs.\n3. Confirm clock synchronization (NTP) between services - token validation fails on clock skew.\n4. After recovery, monitor login success rate to confirm resolution.',
     'authentication,login,401,identity service,certificate,tls,restart,sso',
     'system',
     NOW(),
     0),

    ('KB-103',
     'Disk full on application servers',
     'Services crash or fail to write data; system alerts report 100% disk usage on the application volume. New log writes and file uploads fail.',
     'Unbounded application log growth: log rotation was not configured (or stopped working), so log files accumulated until the disk filled up.',
     '1. Free space immediately by compressing or removing the oldest rotated/archived log files.\n2. Configure log rotation (e.g. logrotate or the logging framework rolling policy) with size/time-based triggers and a bounded retention count.\n3. Enable compression of rotated files and ship older logs to centralized storage.\n4. Add disk-usage monitoring alerts at 80%/90% thresholds to catch recurrence early.',
     'disk,full,storage,log rotation,logrotate,cleanup,space',
     'system',
     NOW(),
     0);
